-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 21-10-2020 a las 23:57:13
-- Versión del servidor: 10.4.8-MariaDB
-- Versión de PHP: 7.3.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `proyect`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `personas`
--

CREATE TABLE `personas` (
  `ID` varchar(100) NOT NULL,
  `Alias` varchar(100) NOT NULL,
  `Apellidos` varchar(100) NOT NULL,
  `Nombre` varchar(100) NOT NULL,
  `Dirección` varchar(100) NOT NULL,
  `Población` varchar(100) NOT NULL,
  `Teléfono` int(100) NOT NULL,
  `Móvil` int(100) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Sexo` varchar(100) NOT NULL,
  `Fecha Nacimiento` date NOT NULL,
  `Estado Civil` varchar(100) NOT NULL,
  `Hijos` int(100) NOT NULL,
  `Desempleado` varchar(100) NOT NULL,
  `Profesión` varchar(100) NOT NULL,
  `Nivel académico` varchar(100) NOT NULL,
  `Lengua usual` varchar(100) NOT NULL,
  `Ingresos mensuales` int(100) NOT NULL,
  `Ahorros` int(100) NOT NULL,
  `Peso` int(100) NOT NULL,
  `Altura` int(100) NOT NULL,
  `Cabello` varchar(100) NOT NULL,
  `Ojos` varchar(100) NOT NULL,
  `Fumador` varchar(100) NOT NULL,
  `Salud` varchar(100) NOT NULL,
  `Afición1` varchar(100) NOT NULL,
  `Afición2` varchar(100) NOT NULL,
  `Característica1` varchar(100) NOT NULL,
  `Característica2` varchar(100) NOT NULL,
  `Valora1` varchar(100) NOT NULL,
  `Valora2` varchar(100) NOT NULL,
  `Fobias` varchar(100) NOT NULL,
  `Sexualidad` varchar(100) NOT NULL,
  `Disponible` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `personas`
--

INSERT INTO `personas` (`ID`, `Alias`, `Apellidos`, `Nombre`, `Dirección`, `Población`, `Teléfono`, `Móvil`, `Email`, `Sexo`, `Fecha Nacimiento`, `Estado Civil`, `Hijos`, `Desempleado`, `Profesión`, `Nivel académico`, `Lengua usual`, `Ingresos mensuales`, `Ahorros`, `Peso`, `Altura`, `Cabello`, `Ojos`, `Fumador`, `Salud`, `Afición1`, `Afición2`, `Característica1`, `Característica2`, `Valora1`, `Valora2`, `Fobias`, `Sexualidad`, `Disponible`) VALUES
('1101', 'Africa', 'AROCAS PASADAS', 'ESTEFANIA', 'PADR? , 109', 'Zaragoza', 938205580, 546212121, 'africa@altecom.es', 'Mujer', '0000-00-00', 'Otros', 1, 'FALSO', 'Administrativo/a', 'Bachillerato', 'catal?n', 1500, 0, 73, 2, 'Casta?o;Marrones', 'VERDADERO', 'Buena', 'Cine', 'TV', 'Sencillez', 'Ternura', 'Buen Humor', 'Realismo', '', 'Bisexual', 'FALSO', ''),
('1102', 'Agata', 'VISO GILABERT', 'QUERALT', 'CASA CORDELLAS , ', 'Barcelona', 936545115, 625215452, 'agata@hotmail.com', 'Mujer', '0000-00-00', 'Otros', 0, 'VERDADERO', 'Delineante', 'EGB', 'castellano', 1100, 113000, 98, 2, 'Negro', 'Marrones', 'FALSO', 'Regular', 'Caminar', 'M?sica', 'Sencillez', 'Sinceridad', 'Serenidad', 'Buen Humor', '', 'Heterosexual', 'VERDADERO'),
('1103', 'Aguador', 'AYALA FERRERAS', 'JOAN', 'DOCTOR FLEMING , 11', 'Zaragoza', 938202768, 649212123, '', 'Hombre', '0000-00-00', 'Otros', 0, 'FALSO', '', 'Diplomado/a', 'castellano', 1500, 0, 61, 2, 'Negro', 'Otro', 'VERDADERO', 'Buena', 'M?sica', 'Cine', 'Sinceridad', 'Realismo', 'Buen Humor', 'Ternura', '', 'No declarada', 'FALSO'),
('1104', 'Albatros', 'BAEZ TEJADO', 'JOAN', 'BERTRAND I SERRA , 11, 3R.', 'Zaragoza', 938727844, 0, 'albatros@wandoo.es', 'Hombre', '0000-00-00', 'Separado/a', 1, 'FALSO', 'Contable', 'Bachillerato', 'catal?n', 1900, 0, 70, 2, 'Otros', 'Marrones', 'FALSO', 'Buena', 'Caminar', 'M?sica', 'Sinceridad', 'Inteligencia', 'Ternura', 'Sinceridad', '', 'Homosexual', 'VERDADERO'),
('1105', 'Albert', 'BASTARDES SOTO', 'MARC', 'CARRI? , 12, 5? A', 'Tarragona', 938350521, 0, 'albert@intercom.es', 'Hombre', '0000-00-00', 'Soltero/a', 3, 'FALSO', 'Dependiente/a', 'Elementales', 'catal?n', 1100, 0, 91, 2, 'Negro', 'Azules', 'FALSO', 'Regular', 'Deporte', 'Deporte', 'Ternura', 'Fortaleza', 'Ternura', 'Romanticismo', 'La TV', 'Heterosexual', 'FALSO'),
('1106', 'Alien', 'ANGUERA VILAFRANCA', 'JOSEP', 'PIRINEUS , 10', 'Valencia', 938755645, 0, 'alien@intercom.es', 'Hombre', '0000-00-00', 'Casado/a', 1, 'FALSO', 'Estudiante', 'FP', 'euskara', 500, 0, 53, 2, 'Negro', 'Verdes', 'FALSO', 'Regular', 'Cine', 'Deporte', 'Buen Humor', 'Fortaleza', 'Serenidad', 'Ternura', '', 'Homosexual', 'VERDADERO'),
('1107', 'amores', 'PASCUAL ALOY', 'ESTHER', 'JACINT VERDAGUER , 43', 'Sevilla', 936520547, 0, 'amores@hotmail.com', 'Mujer', '0000-00-00', 'Divorciado/a', 0, 'FALSO', '', 'Diplomado/a', 'catal?n', 2500, 0, 60, 2, 'Calvo', 'Otro', 'FALSO', 'Buena', 'TV', 'Cine', 'Inteligencia', 'Sinceridad', 'Romanticismo', 'Sinceridad', '', 'Bisexual', 'FALSO'),
('1108', 'Anabel', 'VALL?S GIRVENT', 'LAURA', 'NOU , 9, 2N.', 'Tarragona', 936565656, 645121212, 'anabel@altecom.es', 'Mujer', '0000-00-00', 'Casado/a', 1, 'VERDADERO', 'Conductor/a', 'EGB', 'catal?n', 0, 17500, 70, 2, 'Pelirrojo', 'Verdes', 'VERDADERO', 'Regular', 'Cine', 'M?sica', 'Romanticismo', 'Ternura', 'Sencillez', 'Realismo', '', 'Heterosexual', 'FALSO'),
('1109', 'Antiga', 'RAYA GARCIA', 'RAQUEL', 'JACINT VERDAGUER , 52, 3R, 1A.', 'Barcelona', 936752156, 0, 'antiga@minorisa.es', 'Mujer', '0000-00-00', 'Casado/a', 1, 'FALSO', 'Oficial', 'FP', 'catal?n', 800, 0, 65, 2, 'Rubio', 'Azules', 'FALSO', 'Regular', 'Deporte', 'M?sica', 'Sinceridad', 'Fortaleza', 'Alegr?a', 'Realismo', 'Los d?as lluviosos', 'Bisexual', 'VERDADERO'),
('1110', 'ballador', 'ANDREU CRUZ', 'JOAN', 'JOAN MIR? , 10', 'Tarragona', 938300025, 648221111, 'ballador@hotmail.com', 'Hombre', '0000-00-00', 'Otros', 1, 'VERDADERO', 'Recepcionista', 'EGB', 'catal?n', 1200, 87800, 99, 2, 'Casta?o;Otro', 'VERDADERO', 'Buena', 'Cine', 'TV', 'Alegr?a', 'Ternura', 'Romanticismo', 'Alegr?a', '', 'No declarada', 'VERDADERO', ''),
('1111', 'balladora', 'BARALD?S COMAS', 'MARIA ISABEL', 'JAUME GALOBART , 12', 'Barcelona', 938385567, 658444412, 'balladora@altecom.es', 'Mujer', '0000-00-00', 'Divorciado/a', 0, 'VERDADERO', 'Dise?ador/a', 'Elementales', 'catal?n', 800, 71000, 87, 2, 'Otros', 'Otro', 'FALSO', 'Buena', 'Cine', 'M?sica', 'Fortaleza', 'Inteligencia', 'Buen Humor', 'Inteligencia', '', 'Homosexual', 'VERDADERO'),
('1112', 'Barbilla', 'BERENGUERAS CULLER?S', 'ADRI?', 'PINTOR SERT , 12, 1R., 1A.', 'Valencia', 937809812, 654899994, 'barbilla@hotmail.com', 'Hombre', '0000-00-00', 'Soltero/a', 0, 'VERDADERO', 'Comercial', 'Elementales', 'catal?n', 300, 34300, 92, 2, 'Calvo', 'Marrones', 'VERDADERO', 'Regular', 'M?sica', 'Lectura', 'Buen Humor', 'Romanticismo', 'Ternura', 'Romanticismo', '', 'Heterosexual', 'VERDADERO'),
('1113', 'Besugo', 'L?PEZ DE PABLO GARCIA UCEDA', 'GERARD', 'BELLAVISTA , 30', 'Zaragoza', 936520741, 0, 'besugo@minorisa.es', 'Hombre', '0000-00-00', 'Divorciado/a', 0, 'FALSO', 'Comercial', 'EGB', 'catal?n', 400, 0, 66, 2, 'Negro', 'Otro', 'FALSO', 'Buena', 'Caminar', 'Deporte', 'Ternura', 'Realismo', 'Romanticismo', 'Sencillez', 'La gente gorda', 'Bisexual', 'VERDADERO'),
('1114', 'Bogart', 'ARNAU MORENO', 'ELIOT', 'MONTURIOL , 10, 1R.', 'Sevilla', 938202456, 0, 'bogart@terra.es', 'Hombre', '0000-00-00', 'Soltero/a', 2, 'FALSO', 'Asesor/a fiscal', 'Elementales', 'castellano', 3100, 0, 53, 2, 'Negro', 'Negros', 'FALSO', 'Buena', 'Lectura', 'Cine', 'Ternura', 'Serenidad', 'Sinceridad', 'Buen Humor', '', 'Homosexual', 'VERDADERO'),
('1115', 'Bond', 'RAYA GAVILAN', 'JORDI', 'JACINT VERDAGUER , 52, 2N., 4A.', 'Barcelona', 938754554, 0, 'bond@terra.es', 'Hombre', '0000-00-00', 'Casado/a', 1, 'FALSO', 'Arquitecto/a', 'Licenciado/a', 'gallego', 1000, 0, 101, 2, 'Casta?o;Otro', 'FALSO', 'Regular', 'TV', 'Cine', 'Sinceridad', 'Romanticismo', 'Alegr?a', 'Buen Humor', '', 'Bisexual', 'FALSO', ''),
('1116', 'Borreguero', 'ZAMBUDIO FIGULS', 'LLU?S', 'CASA NOVA , ', 'Barcelona', 936875544, 625411320, '', 'Hombre', '0000-00-00', 'Soltero/a', 1, 'VERDADERO', '', 'EGB', 'catal?n', 1100, 113600, 104, 2, 'Rubio', 'Verdes', 'FALSO', 'Regular', 'Cine', 'M?sica', 'Inteligencia', 'Sencillez', 'Inteligencia', 'Sinceridad', '', 'No declarada', 'VERDADERO'),
('1117', 'Cabeza larga', 'BIDAULT CULLER?S', 'LAURA', 'DE LA CA?A , 12, 1R., C', 'Valencia', 935880712, 690522200, 'cabeza larga@cataloniamail.com', 'Mujer', '0000-00-00', 'Casado/a', 0, 'VERDADERO', 'Contable', 'Licenciado/a', 'castellano', 500, 10900, 74, 2, 'Pelirrojo', 'Negros', 'VERDADERO', 'Buena', 'Lectura', 'TV', 'Buen Humor', 'Sencillez', 'Sinceridad', 'Inteligencia', '', 'Bisexual', 'VERDADERO'),
('1118', 'Caga-novias', 'BIOSCA FONTANET', 'JORDI', 'PINTOR SERT , 12, 2N., 1A.', 'Zaragoza', 936875255, 647821111, '', 'Hombre', '0000-00-00', 'Otros', 3, 'FALSO', 'Camarero/a', 'EGB', 'catal?n', 600, 0, 107, 2, 'Calvo', 'Azules', 'FALSO', 'Buena', 'Cine', 'TV', 'Sencillez', 'Ternura', 'Buen Humor', 'Realismo', '', 'Homosexual', 'VERDADERO'),
('1119', 'Calandria', 'ZAFRA FIGULS', 'DOUNYA', 'CASA SARA , ', 'Tarragona', 936542775, 0, '', 'Mujer', '0000-00-00', 'Separado/a', 1, 'VERDADERO', '', 'EGB', 'castellano', 400, 91400, 107, 2, 'Otros', 'Marrones', 'VERDADERO', 'Regular', 'M?sica', 'Caminar', 'Fortaleza', 'Romanticismo', 'Alegr?a', 'Serenidad', 'La gente prepotente', 'No declarada', 'VERDADERO'),
('1120', 'Cangur', 'ALEU ICART', 'JULIO', 'ART?S , 1, 1R, 1A.', 'Barcelona', 938773545, 0, 'cangur@intercom.es', 'Hombre', '0000-00-00', 'Otros', 0, 'VERDADERO', 'Recepcionista', 'Elementales', 'catal?n', 1100, 102800, 79, 2, 'Casta?o;Azules', 'FALSO', 'Excelente', 'M?sica', 'Lectura', 'Fortaleza', 'Ternura', 'Sinceridad', 'Sencillez', '', 'No declarada', 'FALSO', ''),
('1121', 'Cantinflas', 'BADIA TORN?', 'ANDREU', 'GENERAL PRIM , 11, 2N.', 'Valencia', 938200022, 0, '', 'Hombre', '0000-00-00', 'Separado/a', 1, 'FALSO', 'Recepcionista', 'Diplomado/a', 'euskara', 1000, 0, 106, 2, 'Rubio', 'Verdes', 'FALSO', 'Regular', 'Lectura', 'Caminar', 'Sinceridad', 'Romanticismo', 'Romanticismo', 'Sencillez', '', 'Heterosexual', 'VERDADERO'),
('1122', 'Canto', 'MORALES GESE', 'RAMON', 'CAU DE LA GUINEU , 4', 'Tarragona', 936512545, 0, '', 'Hombre', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Abogado/a', 'EGB', 'catal?n', 1100, 0, 70, 2, 'Calvo', 'Verdes', 'FALSO', 'Buena', 'Lectura', 'Deporte', 'Inteligencia', 'Buen Humor', 'Alegr?a', 'Sinceridad', '', 'Heterosexual', 'VERDADERO'),
('1123', 'Caparranas', 'BLANCO FONTANET', 'DAVID-JESE', 'JOAN SANMART? , 12, 2N., 2A.', 'Barcelona', 937785655, 632548744, 'caparranas@altecom.es', 'Hombre', '0000-00-00', 'Otros', 1, 'FALSO', '', 'Elementales', 'castellano', 500, 0, 61, 2, 'Negro', 'Azules', 'FALSO', 'Buena', 'Deporte', 'Lectura', 'Fortaleza', 'Romanticismo', 'Fortaleza', 'Buen Humor', '', 'Bisexual', 'VERDADERO'),
('1124', 'Cara corta', 'ALVAREZ FERN?NDEZ', 'ARAN', 'PROL. PADR? , 1, 3R. 1A.', 'Madrid', 938300385, 632986321, '', 'Hombre', '0000-00-00', 'Soltero/a', 2, 'FALSO', 'Taxista', 'Elementales', 'castellano', 1400, 0, 85, 2, 'Casta?o;Marrones', 'VERDADERO', 'Buena', 'Deporte', 'Cine', 'Fortaleza', 'Ternura', 'Serenidad', 'Ternura', '', 'Homosexual', 'VERDADERO', ''),
('1125', 'cari?osa', 'GARCIA ALMOGUERA', 'GEMMA', 'SALLENT , 22, 2N.', 'Barcelona', 936520471, 647111021, '', 'Mujer', '0000-00-00', 'Soltero/a', 0, 'FALSO', '', 'Bachillerato', 'catal?n', 1300, 0, 75, 2, 'Pelirrojo', 'Azules', 'FALSO', 'Regular', 'TV', 'TV', 'Realismo', 'Fortaleza', 'Sinceridad', 'Sencillez', 'Los pol?ticos', 'Bisexual', 'FALSO'),
('1126', 'Carretero', 'LIBORI FIGUERAS', 'IVAN', 'JOAN MIR? , 3', 'Sevilla', 936012445, 625481111, 'carretero@intercom.es', 'Hombre', '0000-00-00', 'Divorciado/a', 0, 'FALSO', '', 'EGB', 'castellano', 300, 0, 88, 2, 'Otros', 'Otro', 'VERDADERO', 'Buena', 'Caminar', 'Cine', 'Ternura', 'Sinceridad', 'Buen Humor', 'Ternura', '', 'No declarada', 'VERDADERO'),
('1127', 'Cela', 'BIDAULT PUEYO', 'DAVID', 'LLU?S CASTELLS , 12, 2N.', 'Barcelona', 934500611, 0, 'cela@altecom.es', 'Hombre', '0000-00-00', 'Divorciado/a', 0, 'VERDADERO', 'Oficial', 'EGB', 'franc?s', 500, 120300, 102, 2, 'Rubio', 'Otro', 'FALSO', 'Regular', 'Caminar', 'Deporte', 'Realismo', 'Ternura', 'Alegr?a', 'Fortaleza', '', 'Bisexual', 'VERDADERO'),
('1128', 'Coco', 'BENITEZ JOSE', 'XAVIER', 'SANT VALENT? , 12, 1R.', 'Sevilla', 937885544, 0, 'coco@hotmail.com', 'Hombre', '0000-00-00', 'Divorciado/a', 2, 'FALSO', 'Asesor/a fiscal', 'Elementales', 'catal?n', 1100, 0, 69, 2, 'Rubio', 'Azules', 'VERDADERO', 'Regular', 'Deporte', '#N/A', 'Alegr?a', 'Sinceridad', 'Sinceridad', 'Ternura', 'Viajar en avi?n;Heterosexual', 'FALSO', ''),
('1129', 'Conejo', 'PASCUAL FLORES', 'MARIO', '?NGEL GUIMER? , 43, 2N', 'Sevilla', 936512105, 0, 'conejo@minorisa.es', 'Hombre', '0000-00-00', 'Separado/a', 1, 'FALSO', '', 'Elementales', 'castellano', 900, 0, 73, 2, 'Casta?o;Verdes', 'FALSO', 'Fatal', 'M?sica', 'Deporte', 'Realismo', 'Alegr?a', 'Realismo', 'Sinceridad', '', 'Heterosexual', 'VERDADERO', ''),
('1130', 'Corcel', 'AYALA TORN?', 'JESUS', 'JAUME GALOBART , 11', 'Sevilla', 938202200, 0, 'corcel@altecom.es', 'Hombre', '0000-00-00', 'Separado/a', 1, 'FALSO', 'Dependiente/a', 'FP', 'catal?n', 0, 0, 71, 2, 'Negro', 'Marrones', 'FALSO', 'Regular', 'TV', 'Caminar', 'Alegr?a', 'Sinceridad', 'Ternura', 'Sinceridad', '', 'Homosexual', 'VERDADERO'),
('1131', 'Cuca', 'LISTAN FIGUERAS', 'GEMMA', 'AVINGUDA TRES , 3, 1R., 1A.', 'Madrid', 939965585, 0, '', 'Mujer', '0000-00-00', 'Divorciado/a', 0, 'FALSO', 'Arquitecto/a', 'FP', 'catal?n', 800, 0, 77, 2, 'Negro', 'Negros', 'FALSO', 'Buena', 'TV', 'Cine', 'Realismo', 'Serenidad', 'Sinceridad', 'Inteligencia', '', 'Homosexual', 'VERDADERO'),
('1132', 'Curie', 'RASERO GAVILAN', 'SILVIA', 'JACINT VERDAGUER , 52, 2N., 1A.', 'Barcelona', 936541235, 648555214, 'curie@minorisa.es', 'Mujer', '0000-00-00', 'Soltero/a', 1, 'FALSO', '', 'Elementales', 'catal?n', 0, 0, 104, 2, 'Negro', 'Marrones', 'FALSO', 'Buena', 'Deporte', 'Cine', 'Inteligencia', 'Ternura', 'Inteligencia', 'Fortaleza', 'Los huevos fritos', 'No declarada', 'VERDADERO'),
('1133', 'Dal?;ARNALOT PUIG', 'ALBERT', 'DIPUTACI? , 10', 'Barcelona', '938204054', 621114452, 0, 'Hombre', '20/06/69', '0000-00-00', '', 0, 'Profesor/a', 'Doctor/a', 'catal?n', '1200', 0, 59, 2, 0, 'Verdes', 'VERDADERO', 'Buena', 'Lectura', 'Cine', 'Sencillez', 'Ternura', 'Sinceridad', 'Buen Humor', '', 'Bisexual', 'FALSO', ''),
('1134', 'Diamant', 'MOLINER GARRIDO', 'MARIA', 'VIC , 39, 1R., 2A.', 'Tarragona', 936584541, 0, '', 'Mujer', '0000-00-00', 'Casado/a', 1, 'VERDADERO', 'Camarero/a', 'EGB', 'catal?n', 2400, 15100, 106, 2, 'Pelirrojo', 'Azules', 'FALSO', 'Buena', 'Deporte', 'Caminar', 'Ternura', 'Buen Humor', 'Fortaleza', 'Sinceridad', 'Barcelona', 'Heterosexual', 'FALSO'),
('1135', 'Dol?a', 'GALOBART GARCIA', 'BERTA', 'GERMAN DURAN , 21', 'Zaragoza', 934111475, 0, 'dol?a@cidet.com', 'Mujer', '0000-00-00', 'Separado/a', 0, 'FALSO', 'Contable', 'FP', 'castellano', 1200, 0, 58, 2, 'Pelirrojo', 'Negros', 'VERDADERO', 'Regular', 'Deporte', 'Caminar', 'Sinceridad', 'Buen Humor', 'Realismo', 'Serenidad', '', 'Bisexual', 'FALSO'),
('1136', 'Dorada', 'L?PEZ GARRIGASSAIT', 'BERTA', 'BELLAVISTA , 30', 'Zaragoza', 935687444, 0, 'dorada@intercom.es', 'Mujer', '0000-00-00', 'Otros', 0, 'FALSO', 'Administrativo/a', 'EGB', 'castellano', 1400, 0, 80, 2, 'Otros', 'Verdes', 'FALSO', 'Regular', 'TV', 'Caminar', 'Buen Humor', 'Realismo', 'Inteligencia', 'Alegr?a', 'Los coches', 'Bisexual', 'VERDADERO'),
('1137', 'Elisa', 'S?NCHEZ G?MEZ', 'MIREIA', 'NOU , 7, 2N.', 'Barcelona', 936658711, 645874112, 'elisa@altecom.es', 'Mujer', '0000-00-00', 'Soltero/a', 0, 'FALSO', 'Administrativo/a', 'Elementales', 'castellano', 1200, 0, 66, 2, 'Rubio', 'Otro', 'VERDADERO', 'Excelente', 'Deporte', 'TV', 'Fortaleza', 'Sinceridad', 'Ternura', 'Realismo', 'Los pol?ticos', 'Homosexual', 'VERDADERO'),
('1138', 'Encarna', 'ALAVEDRA SUNY?', 'GEMMA', 'MANELIC , 1', 'Barcelona', 938773941, 632125482, 'encarna@hotmail.com', 'Mujer', '0000-00-00', 'Casado/a', 1, 'FALSO', 'Dependiente/a', 'Elementales', 'catal?n', 1000, 0, 66, 2, 'Otros', 'Negros', 'FALSO', 'Regular', 'Lectura', 'Deporte', 'Fortaleza', 'Inteligencia', 'Sinceridad', 'Fortaleza', '', 'No declarada', 'FALSO'),
('1139', 'entesa', 'ALIGU? BONVEH?', 'MARIA ISABEL', 'DE LA PESCA , 1, 1R., 1A.', 'Barcelona', 938305295, 0, 'entesa@altecom.es', 'Mujer', '0000-00-00', 'Casado/a', 0, 'VERDADERO', 'Asesor/a fiscal', 'Bachillerato', 'castellano', 0, 62600, 68, 2, 'Pelirrojo', 'Otro', 'FALSO', 'Buena', 'Lectura', 'Cine', 'Buen Humor', 'Serenidad', 'Inteligencia', 'Fortaleza', '', 'Bisexual', 'FALSO'),
('1140', 'Entierravivos', 'MAS FRANCH', 'TONI', 'PIRINEUS , 34', 'Barcelona', 936524446, 621445221, '', 'Hombre', '0000-00-00', 'Divorciado/a', 1, 'VERDADERO', '', 'EGB', 'catal?n', 0, 54700, 54, 2, 'Otros', 'Marrones', 'FALSO', 'Regular', 'TV', 'M?sica', 'Ternura', 'Sinceridad', 'Serenidad', 'Realismo', '', 'No declarada', 'VERDADERO'),
('1141', 'Esportista', 'ALOY COMPTE', 'ALEJANDRO', 'PROL. JACINT VERDAGUER , 1, 2N., 2A.', 'Madrid', 938305551, 0, '', 'Hombre', '0000-00-00', 'Divorciado/a', 0, 'FALSO', '', 'FP', 'catal?n', 1400, 0, 78, 2, 'Negro', 'Otro', 'FALSO', 'Regular', 'Cine', 'TV', 'Fortaleza', 'Realismo', 'Sencillez', 'Serenidad', '', 'Bisexual', 'VERDADERO'),
('1142', 'ET', 'ASENSIO VEGA', 'JOAN MART?', 'MALLORCA , 11', 'Zaragoza', 938206097, 0, 'et@altecom.es', 'Hombre', '0000-00-00', 'Otros', 2, 'FALSO', 'Taxista', 'Bachillerato', 'catal?n', 1300, 0, 91, 2, 'Rubio', 'Negros', 'VERDADERO', 'Regular', 'M?sica', 'M?sica', 'Buen Humor', 'Serenidad', 'Realismo', 'Serenidad', '', 'Bisexual', 'VERDADERO'),
('1143', 'Europa', 'BIDAULT P?REZ', 'INGRID', 'SANT BENET , 12, 2N.', 'Barcelona', 934500644, 0, '', 'Mujer', '0000-00-00', 'Casado/a', 0, 'FALSO', '', 'Licenciado/a', 'catal?n', 1200, 0, 53, 2, 'Casta?o;Marrones', 'FALSO', 'Buena', 'Caminar', 'Lectura', 'Romanticismo', 'Alegr?a', 'Fortaleza', 'Inteligencia', '', 'Heterosexual', 'FALSO', ''),
('1144', 'expert', 'ALOY CODINACHS', 'OLIVER', 'PROL. PADR? , 1, 2N., 2A.', 'Barcelona', 938305594, 0, '', 'Hombre', '0000-00-00', 'Otros', 1, 'FALSO', 'Representante', 'Licenciado/a', 'castellano', 1100, 0, 79, 2, 'Casta?o;Negros', 'VERDADERO', 'Fatal', 'Deporte', 'Cine', 'Fortaleza', 'Serenidad', 'Romanticismo', 'Sinceridad', 'Los huevos fritos', 'No declarada', 'VERDADERO', ''),
('1145', 'experta', 'ALTIMIRAS ARMENTEROS', 'SANDRA', 'ART?S , 1, 2N., 2A.', 'Barcelona', 938300422, 0, 'experta@wandoo.es', 'Mujer', '0000-00-00', 'Separado/a', 1, 'FALSO', 'Camarero/a', 'EGB', 'castellano', 1100, 0, 110, 2, 'Calvo', 'Verdes', 'FALSO', 'Fatal', 'Deporte', 'Lectura', 'Ternura', 'Realismo', 'Romanticismo', 'Inteligencia', '', 'Bisexual', 'VERDADERO'),
('1146', 'F50', 'BELMONTE S?NCHEZ', 'JORDI', 'JOAN XXIII , 12, 1R, 2A.', 'Madrid', 938350511, 621455662, 'f5@wandoo.es', 'Hombre', '0000-00-00', 'Otros', 1, 'FALSO', 'Enfermero/a', 'Diplomado/a', 'catal?n', 1500, 0, 105, 2, 'Casta?o;Azules', 'FALSO', 'Regular', 'M?sica', 'M?sica', 'Alegr?a', 'Ternura', 'Sinceridad', 'Ternura', 'Barcelona', 'Homosexual', 'FALSO', ''),
('1147', 'Faja Ancha', 'BAJONA GARCIA', 'MARC', 'BERTRAND I SERRA , 11, 3R.', 'Zaragoza', 938727589, 0, '', 'Hombre', '0000-00-00', 'Otros', 2, 'FALSO', '', 'Elementales', 'catal?n', 1300, 0, 60, 2, 'Rubio', 'Verdes', 'FALSO', 'Buena', 'M?sica', 'Lectura', 'Ternura', 'Sinceridad', 'Serenidad', 'Realismo', 'Los ni?os', 'Homosexual', 'VERDADERO'),
('1148', 'Fara', 'AGUILAR RODRIGUEZ', 'JORDINA', 'LA SARDANA , 1', 'Barcelona', 938208488, 0, '', 'Mujer', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Contable', 'Bachillerato', 'catal?n', 600, 0, 87, 2, 'Calvo', 'Marrones', 'FALSO', 'Buena', 'TV', 'M?sica', 'Buen Humor', 'Fortaleza', 'Ternura', 'Inteligencia', 'Los coches', 'Heterosexual', 'FALSO'),
('1149', 'Fina', 'BARRIGA SOTO', 'MARIA JOS?', 'GALILEU , 12', 'Tarragona', 938320587, 0, 'fina@hotmail.com', 'Mujer', '0000-00-00', 'Otros', 2, 'FALSO', '', 'Elementales', 'ingl?s', 1100, 0, 70, 2, 'Otros', 'Negros', 'VERDADERO', 'Regular', 'M?sica', 'Caminar', 'Sinceridad', 'Realismo', 'Ternura', 'Inteligencia', '', 'Homosexual', 'FALSO'),
('1150', 'Fuego', 'AVILA MASJUAN', 'RAQUEL', 'SANT VALENT? , 11', 'Sevilla', 938203095, 658954422, 'fuego@altecom.es', 'Mujer', '0000-00-00', 'Separado/a', 0, 'FALSO', 'Comercial', 'Elementales', 'castellano', 600, 0, 70, 2, 'Negro', 'Otro', 'FALSO', 'Regular', 'Lectura', '#N/A', 'Sinceridad', 'Alegr?a', 'Sencillez', 'Sinceridad', '', 'No declarada', 'VERDADERO'),
('1151', 'Galgo', 'PARRAMON FLORES', 'ENRIC', 'JOAN XXIII , 43', 'Barcelona', 934555455, 0, '', 'Hombre', '0000-00-00', 'Otros', 0, 'FALSO', 'Dependiente/a', 'EGB', 'castellano', 1000, 0, 78, 2, 'Casta?o;Otro', 'VERDADERO', 'Regular', 'Lectura', 'Caminar', 'Fortaleza', 'Realismo', 'Alegr?a', 'Ternura', '', 'Homosexual', 'VERDADERO', ''),
('1152', 'Garota', 'AGUILAR RAMOS', 'MARTA', 'DE LA PAU , 1', 'Tarragona', 938208502, 0, 'garota@hotmail.com', 'Mujer', '0000-00-00', 'Separado/a', 2, 'FALSO', 'Recepcionista', 'EGB', 'castellano', 400, 0, 62, 2, 'Otros', 'Otro', 'FALSO', 'Buena', 'Caminar', 'M?sica', 'Sencillez', 'Romanticismo', 'Romanticismo', 'Sencillez', '', 'Homosexual', 'FALSO'),
('1153', 'gata', 'AYALA ALSINA', 'CARLA', 'SANT ANTONI MARIA CLARET , 11', 'Zaragoza', 938205245, 0, '', 'Mujer', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Administrativo/a', 'EGB', 'catal?n', 800, 0, 103, 2, 'Otros', 'Verdes', 'VERDADERO', 'Buena', 'TV', 'Lectura', 'Inteligencia', 'Sinceridad', 'Fortaleza', 'Sencillez', '', 'Heterosexual', 'FALSO'),
('1154', 'Gateta', 'ALVAREZ TROYANO', 'MARIA NOELIA', 'AVINGUDA TRES , 1, 3R., 1A.', 'Tarragona', 938300374, 0, 'gateta@cataloniamail.com', 'Mujer', '0000-00-00', 'Divorciado/a', 0, 'FALSO', 'Enfermero/a', 'Bachillerato', 'castellano', 1200, 0, 66, 2, 'Rubio', 'Azules', 'FALSO', 'Buena', 'Caminar', 'TV', 'Buen Humor', 'Ternura', 'Buen Humor', 'Sinceridad', '', 'Heterosexual', 'FALSO'),
('1155', 'Gioconda', 'ALINS GONZ?LEZ', 'CRISTINA', 'PROL. PADR? , 1, 2N., 1A.', 'Barcelona', 938305576, 652148555, '', 'Mujer', '0000-00-00', 'Soltero/a', 1, 'FALSO', '', 'Bachillerato', 'castellano', 1200, 0, 102, 2, 'Negro', 'Azules', 'FALSO', 'Regular', 'Caminar', 'M?sica', 'Ternura', 'Buen Humor', 'Serenidad', 'Realismo', '', 'Heterosexual', 'VERDADERO'),
('1156', 'Groucho', 'ACU?A TORT', 'CARLOS', 'SANT JOAN , 0, C, 3R. A', 'Valencia', 938208614, 0, 'groucho@intercom.es', 'Hombre', '0000-00-00', 'Divorciado/a', 1, 'FALSO', '', 'Licenciado/a', 'catal?n', 1000, 0, 79, 2, 'Rubio', 'Negros', 'FALSO', 'Buena', 'Cine', 'Deporte', 'Buen Humor', 'Ternura', 'Serenidad', 'Realismo', 'Viajar en avi?n;Homosexual', 'VERDADERO', ''),
('1157', 'Harpo', 'ALGU? TRANCHO', 'DAVID', 'PROL. JACINT VERDAGUER , 1, 1R., 1A.', 'Madrid', 938770077, 0, 'harpo@hotmail.com', 'Hombre', '0000-00-00', 'Soltero/a', 1, 'VERDADERO', 'Funcionario/a', 'Diplomado/a', 'ingl?s', 3000, 62000, 82, 2, 'Casta?o;Marrones', 'FALSO', 'Regular', 'Lectura', 'M?sica', 'Fortaleza', 'Alegr?a', 'Ternura', 'Alegr?a', 'Viajar en avi?n;Heterosexual', 'VERDADERO', '', ''),
('1158', 'Hispa', 'BADIA CASTILLO', 'CRISTIAN', 'JOAN XXIII , 11, 1R., 1A.', 'Sevilla', 938200713, 0, 'hispa@cataloniamail.com', 'Hombre', '0000-00-00', 'Soltero/a', 1, 'FALSO', 'Oficial', 'EGB', 'catal?n', 300, 0, 103, 2, 'Rubio', 'Marrones', 'VERDADERO', 'Regular', 'M?sica', 'Deporte', 'Realismo', 'Sencillez', 'Inteligencia', 'Sinceridad', '', 'Heterosexual', 'VERDADERO'),
('1159', 'Hojalatero', 'BENITEZ FLORES', 'JULIO ALBERTO', 'LLU?S CASTELLS , 12, 1R.', 'Barcelona', 938270685, 625477881, '', 'Hombre', '0000-00-00', 'Soltero/a', 0, 'FALSO', 'Representante', 'EGB', 'castellano', 300, 0, 54, 2, 'Negro', 'Negros', 'FALSO', 'Fatal', 'Caminar', 'Lectura', 'Sencillez', 'Realismo', 'Ternura', 'Alegr?a', '', 'Bisexual', 'FALSO'),
('1160', 'Huevo', 'TORRUELLA GARCIA', 'SERGI', 'PADR? , 83', 'Zaragoza', 936021048, 0, 'huevo@terra.es', 'Hombre', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Estudiante', 'Diplomado/a', 'catal?n', 400, 0, 66, 2, 'Negro', 'Verdes', 'VERDADERO', 'Buena', 'Lectura', 'Caminar', 'Inteligencia', 'Sinceridad', 'Serenidad', 'Fortaleza', '', 'Bisexual', 'VERDADERO'),
('1161', 'James Dean', 'ALBERICH RODRIGUEZ', 'ALEIX', 'SANT ISCLE , 1', 'Tarragona', 938773933, 648555552, 'james dean@intercom.es', 'Hombre', '0000-00-00', 'Divorciado/a', 2, 'FALSO', '', 'Doctor/a', 'gallego', 500, 0, 64, 2, 'Calvo', 'Negros', 'FALSO', 'Buena', 'Caminar', 'TV', 'Realismo', 'Ternura', 'Buen Humor', 'Realismo', 'Los entierros', 'No declarada', 'VERDADERO'),
('1162', 'J?ssica', 'ARMENCOT PUIG', 'VER?NICA', 'MONTSERRAT , 10', 'Zaragoza', 938206766, 690254111, 'j?ssica@hotmail.com', 'Mujer', '0000-00-00', 'Soltero/a', 1, 'FALSO', 'Camarero/a', 'EGB', 'catal?n', 1000, 0, 104, 2, 'Calvo', 'Azules', 'VERDADERO', 'Buena', 'Caminar', 'M?sica', 'Serenidad', 'Sencillez', 'Romanticismo', 'Sinceridad', 'Las ciudades', 'No declarada', 'VERDADERO'),
('1163', 'Julia', 'ALIGU? RIVERA', 'MARIONA', 'PROL. JACINT VERDAGUER , 1, 1R., 2A.', 'Zaragoza', 938305223, 0, '', 'Mujer', '0000-00-00', 'Soltero/a', 0, 'FALSO', 'Oficial', 'EGB', 'euskara', 700, 0, 48, 2, 'Calvo', 'Azules', 'FALSO', 'Regular', 'Cine', '#N/A', 'Fortaleza', 'Buen Humor', 'Fortaleza', 'Alegr?a', 'Los perros', 'Homosexual', 'VERDADERO'),
('1164', 'Julio', 'BARRIGA RIU', 'MARC', 'TRABUCAIRES , 12', 'Zaragoza', 938325565, 0, '', 'Hombre', '0000-00-00', 'Divorciado/a', 1, 'FALSO', 'Comercial', 'Bachillerato', 'catal?n', 1400, 0, 89, 2, 'Rubio', 'Negros', 'FALSO', 'Buena', 'Deporte', 'M?sica', 'Alegr?a', 'Fortaleza', 'Sencillez', 'Realismo', '', 'Homosexual', 'VERDADERO'),
('1165', 'Lali', 'PORTELLA GISPETS', 'GEMMA', 'JACINT VERDAGUER , 49, 4T., 2A.', 'Sevilla', 936565448, 632587441, '', 'Mujer', '0000-00-00', 'Soltero/a', 1, 'VERDADERO', 'Dise?ador/a', 'EGB', 'castellano', 1500, 18100, 98, 2, 'Otros', 'Marrones', 'FALSO', 'Buena', 'Lectura', 'Cine', 'Sinceridad', 'Serenidad', 'Alegr?a', 'Sinceridad', '', 'Heterosexual', 'VERDADERO'),
('1166', 'libero', 'AGUILERA BAENA', 'RICARD', 'MANELIC , 1', 'Madrid', 938208360, 0, '', 'Hombre', '0000-00-00', 'Otros', 0, 'FALSO', '', 'Diplomado/a', 'franc?s', 1500, 0, 82, 2, 'Negro', 'Verdes', 'FALSO', 'Fatal', 'Caminar', 'TV', 'Buen Humor', 'Ternura', 'Sencillez', 'Realismo', '', 'Heterosexual', 'FALSO'),
('1167', 'Llus', 'RODRIGUEZ GARC?A', 'JUAN', 'VERGE DE F?TIMA , 6, BX., 2A.', 'Madrid', 936549889, 602412052, 'llus@hotmail.com', 'Hombre', '0000-00-00', 'Otros', 0, 'FALSO', 'Dependiente/a', 'EGB', 'ingl?s', 500, 0, 94, 2, 'Calvo', 'Otro', 'VERDADERO', 'Buena', 'Caminar', 'M?sica', 'Buen Humor', 'Sinceridad', 'Sinceridad', 'Fortaleza', '', 'Heterosexual', 'FALSO'),
('1168', 'Loli', 'AGUILAR SUNY?', 'MARTA', 'SANT JOAN , 0, D, 3R. A', 'Tarragona', 938208677, 0, '', 'Mujer', '0000-00-00', 'Casado/a', 0, 'FALSO', '', 'Elementales', 'castellano', 0, 0, 91, 2, 'Calvo', 'Verdes', 'FALSO', 'Buena', 'Cine', 'Lectura', 'Sencillez', 'Serenidad', 'Buen Humor', 'Sencillez', 'Los hospitales', 'Heterosexual', 'VERDADERO'),
('1169', 'Madonna', 'BARRIGA TARD?', 'NAT?LIA', 'GALILEU , 12', 'Madrid', 938325558, 0, 'madonna@wandoo.es', 'Mujer', '0000-00-00', 'Otros', 1, 'FALSO', 'Delineante', 'Bachillerato', 'castellano', 1100, 0, 95, 2, 'Calvo', 'Otro', 'VERDADERO', 'Regular', 'TV', 'Lectura', 'Sencillez', 'Romanticismo', 'Realismo', 'Inteligencia', 'Los hospitales', 'No declarada', 'FALSO'),
('1170', 'Mata Hari', 'BARCONS LARA', 'MARTA', 'ESPORTS , 12', 'Barcelona', 938360281, 0, 'mata hari@intercom.es', 'Mujer', '0000-00-00', 'Otros', 0, 'FALSO', 'Comercial', 'EGB', 'catal?n', 3000, 0, 110, 2, 'Otros', 'Otro', 'FALSO', 'Regular', 'M?sica', 'Deporte', 'Fortaleza', 'Sencillez', 'Buen Humor', 'Fortaleza', '', 'Heterosexual', 'VERDADERO'),
('1171', 'Melanie', 'AGUILERA TATJ?', 'LAURA', 'JOSEP BOIXADERAS , 1', 'Valencia', 938208380, 625411014, 'melanie@minorisa.es', 'Mujer', '0000-00-00', 'Otros', 1, 'FALSO', '', 'EGB', 'castellano', 700, 0, 96, 2, 'Casta?o;Azules', 'FALSO', 'Regular', 'Caminar', 'Lectura', 'Fortaleza', 'Sencillez', 'Alegr?a', 'Fortaleza', '', 'Homosexual', 'VERDADERO', ''),
('1172', 'Melqu?ades', 'ALEU PRAT', 'JOAN', 'CERVANTES , 1, 1R.', 'Sevilla', 938770878, 0, 'melqu?ades@hotmail.com', 'Hombre', '0000-00-00', 'Otros', 2, 'FALSO', '', 'EGB', 'catal?n', 1500, 0, 93, 2, 'Calvo', 'Azules', 'FALSO', 'Buena', 'Cine', 'TV', 'Alegr?a', 'Realismo', 'Romanticismo', 'Sinceridad', '', 'Heterosexual', 'VERDADERO'),
('1173', 'Merche', 'VALL?S GIRVENT', 'ALEXIA', 'CERVANTES , 9, 1R.', 'Valencia', 936874511, 654822414, 'merche@terra.es', 'Mujer', '0000-00-00', 'Soltero/a', 0, 'VERDADERO', 'Contable', 'Diplomado/a', 'catal?n', 600, 39700, 53, 2, 'Calvo', 'Azules', 'FALSO', 'Regular', 'M?sica', 'Cine', 'Fortaleza', 'Alegr?a', 'Sinceridad', 'Serenidad', 'Los perros', 'Heterosexual', 'VERDADERO'),
('1174', 'Midas', 'MOLINA GARRIDO', 'FERRAN', 'JOAN XXIII , 39', 'Sevilla', 936548745, 698774444, 'midas@cataloniamail.com', 'Hombre', '0000-00-00', 'Soltero/a', 0, 'VERDADERO', 'Dependiente/a', 'EGB', 'castellano', 500, 36100, 59, 2, 'Calvo', 'Otro', 'VERDADERO', 'Excelente', 'M?sica', 'Caminar', 'Buen Humor', 'Realismo', 'Fortaleza', 'Serenidad', 'Los perros', 'Homosexual', 'FALSO'),
('1175', 'Mona lisa', 'ARISSA HERMOSO', 'CRISTINA', 'DOCTOR BARNARD , 10', 'Tarragona', 938755512, 602111254, 'mona lisa@minorisa.es', 'Mujer', '0000-00-00', 'Soltero/a', 0, 'FALSO', '', 'Bachillerato', 'catal?n', 1000, 0, 75, 2, 'Casta?o;Azules', 'FALSO', 'Buena', 'Deporte', 'Cine', 'Ternura', 'Sinceridad', 'Buen Humor', 'Sencillez', '', 'No declarada', 'FALSO', ''),
('1176', 'Moro', 'BARALD?S PARDO', 'JOS? ANTONIO', 'ESPORTS , 12', 'Barcelona', 938722096, 0, 'moro@minorisa.es', 'Hombre', '0000-00-00', 'Separado/a', 0, 'FALSO', 'Asesor/a fiscal', 'Elementales', 'catal?n', 1500, 0, 97, 2, 'Calvo', 'Otro', 'VERDADERO', 'Regular', 'M?sica', 'Cine', 'Realismo', 'Sinceridad', 'Romanticismo', 'Alegr?a', '', 'No declarada', 'VERDADERO'),
('1177', 'Mozart', 'SUAREZ GARZ?N', 'JORDI', 'DE LA PAU , 8', 'Valencia', 934512544, 0, 'mozart@wandoo.es', 'Hombre', '0000-00-00', 'Soltero/a', 1, 'FALSO', 'Taxista', 'EGB', 'catal?n', 1600, 0, 108, 2, 'Casta?o;Negros', 'FALSO', 'Regular', 'Lectura', 'Deporte', 'Serenidad', 'Fortaleza', 'Serenidad', 'Romanticismo', '', 'Heterosexual', 'VERDADERO', ''),
('1178', 'Nadadora', 'ARPA MORENO', 'BEGONYA', 'SANT VALENT? , 11', 'Barcelona', 938205011, 0, '', 'Mujer', '0000-00-00', 'Otros', 1, 'FALSO', 'Dependiente/a', 'Elementales', 'gallego', 800, 0, 106, 2, 'Casta?o;Verdes', 'VERDADERO', 'Buena', 'M?sica', 'TV', 'Alegr?a', 'Romanticismo', 'Serenidad', 'Fortaleza', '', 'Bisexual', 'VERDADERO', ''),
('1179', 'Nalga', 'ALOY FARRANDO', 'INGRID', 'PROL. PADR? , 1, 2N., 2A.', 'Barcelona', 938300864, 0, '', 'Mujer', '0000-00-00', 'Separado/a', 1, 'FALSO', 'Representante', 'EGB', 'gallego', 0, 0, 93, 2, 'Pelirrojo', 'Otro', 'FALSO', 'Regular', 'TV', 'Lectura', 'Inteligencia', 'Buen Humor', 'Sencillez', 'Inteligencia', '', 'Bisexual', 'VERDADERO'),
('1180', 'Napoleon', 'LUQUE GARRIGASAIT', 'MIQUEL', 'VIC , 30 (TORROELLA)', 'Barcelona', 933256844, 625401445, 'napoleon@cidet.com', 'Hombre', '0000-00-00', 'Divorciado/a', 0, 'FALSO', 'Taxista', 'Licenciado/a', 'catal?n', 1000, 0, 93, 2, 'Rubio', 'Azules', 'FALSO', 'Buena', 'Caminar', 'Cine', 'Alegr?a', 'Inteligencia', 'Sencillez', 'Realismo', '', 'Heterosexual', 'FALSO'),
('1181', 'Orondo', 'RID? G?MEZ', 'AGUST?', 'SANT ISCLE , 6', 'Tarragona', 936528779, 0, 'orondo@altecom.es', 'Hombre', '0000-00-00', 'Casado/a', 2, 'FALSO', 'Contable', 'FP', 'castellano', 1000, 0, 79, 2, 'Pelirrojo', 'Negros', 'FALSO', 'Regular', 'Cine', 'Caminar', 'Sinceridad', 'Ternura', 'Sinceridad', 'Buen Humor', 'Los fumadores', 'Bisexual', 'VERDADERO'),
('1182', 'Papagayo', 'SANTAMARIA FLOTATS', 'ANTONI', 'JAUME BALMES , 70, 3R, 1A.', 'Sevilla', 931021886, 0, 'papagayo@altecom.es', 'Hombre', '0000-00-00', 'Soltero/a', 0, 'VERDADERO', 'Profesor/a', 'EGB', 'catal?n', 400, 95000, 89, 2, 'Otros', 'Otro', 'FALSO', 'Buena', 'Caminar', 'Cine', 'Ternura', 'Romanticismo', 'Sinceridad', 'Inteligencia', 'Los ni?os', 'Homosexual', 'VERDADERO'),
('1183', 'Paseante', 'HERMS G?MEZ', 'JOAN', 'GERMAN DURAN , 27, 3R., 1A.', 'Zaragoza', 936201457, 658955442, '', 'Hombre', '0000-00-00', 'Divorciado/a', 1, 'FALSO', 'Camarero/a', 'EGB', 'franc?s', 0, 0, 81, 2, 'Pelirrojo', 'Otro', 'VERDADERO', 'Buena', 'M?sica', 'TV', 'Sinceridad', 'Buen Humor', 'Realismo', 'Romanticismo', '', 'Heterosexual', 'FALSO'),
('1184', 'Pasi?n;ARTIGAS MATURANO', 'M?NICA', 'SANT JOAN , 11', 'Barcelona', '938207515', 0, 0, 'Mujer', '03/10/59', '0000-00-00', '3', 0, 'Funcionario/a', 'EGB', 'catal?n', '1400', 0, 100, 2, 0, 'Otro', 'FALSO', 'Regular', 'Cine', 'Lectura', 'Ternura', 'Sencillez', 'Alegr?a', 'Ternura', 'Los entierros', 'Heterosexual', 'VERDADERO', ''),
('1185', 'Pato', 'AGUILAR MASANA', 'GERARD', 'PUIG , 1', 'Madrid', 938208558, 0, '', 'Hombre', '0000-00-00', 'Casado/a', 2, 'FALSO', 'Arquitecto/a', 'Elementales', 'castellano', 300, 0, 83, 2, 'Rubio', 'Marrones', 'VERDADERO', 'Fatal', 'M?sica', 'Cine', 'Ternura', 'Sinceridad', 'Buen Humor', 'Ternura', '', 'No declarada', 'VERDADERO'),
('1186', 'Pelusa', 'ALTIMIRAS SERAROLS', 'GEMMA', 'PROL. JACINT VERDAGUER , 1, 2N., 2A.', 'Valencia', 938300496, 0, 'pelusa@hotmail.com', 'Mujer', '0000-00-00', 'Casado/a', 4, 'FALSO', 'Funcionario/a', 'Bachillerato', 'catal?n', 1300, 0, 89, 2, 'Calvo', 'Azules', 'FALSO', 'Buena', 'Caminar', 'TV', 'Serenidad', 'Inteligencia', 'Sinceridad', 'Ternura', 'Los dibujos animados', 'Homosexual', 'VERDADERO'),
('1187', 'Perla', 'TORRESCASANA GARCIA', 'MARIA', 'RAMON I CAJAL , 81, 2N.', 'Barcelona', 930120545, 625458445, 'perla@cataloniamail.com', 'Mujer', '0000-00-00', 'Divorciado/a', 0, 'FALSO', 'Asesor/a fiscal', 'FP', 'catal?n', 4000, 0, 63, 2, 'Pelirrojo', 'Negros', 'VERDADERO', 'Excelente', 'Caminar', 'M?sica', 'Realismo', 'Sencillez', 'Serenidad', 'Realismo', 'Los ni?os', 'Heterosexual', 'VERDADERO'),
('1188', 'Picasso', 'ARIZA PUIGB?', 'ORIOL', 'MORAGUES , 10', 'Sevilla', 938207095, 0, '', 'Hombre', '0000-00-00', 'Casado/a', 1, 'VERDADERO', 'Dependiente/a', 'Elementales', 'catal?n', 900, 76400, 79, 2, 'Negro', 'Negros', 'FALSO', 'Regular', 'Cine', 'TV', 'Inteligencia', 'Ternura', 'Alegr?a', 'Realismo', 'Los entierros', 'Homosexual', 'VERDADERO'),
('1189', 'poma', 'ALVAREZ ARMENTEROS', 'VIRGINIA', 'PROL. PADR? , 1, 3R., 2A.', 'Barcelona', 938300214, 0, '', 'Mujer', '0000-00-00', 'Separado/a', 0, 'FALSO', 'Conductor/a', 'Bachillerato', 'catal?n', 0, 0, 66, 2, 'Negro', 'Marrones', 'FALSO', 'Regular', 'Deporte', 'M?sica', 'Romanticismo', 'Sinceridad', 'Sinceridad', 'Inteligencia', '', 'Heterosexual', 'VERDADERO'),
('1190', 'Psicosis', 'BARALD?S TARRAG?', 'DAMI?', 'FRANCESC DE VIT?RIA , 11, 4T 2A', 'Tarragona', 938727244, 625410101, 'psicosis@intercom.es', 'Hombre', '0000-00-00', 'Divorciado/a', 0, 'VERDADERO', 'Camarero/a', 'EGB', 'catal?n', 1600, 103400, 101, 2, 'Casta?o;Negros', 'FALSO', 'Buena', 'TV', 'Deporte', 'Fortaleza', 'Buen Humor', 'Realismo', 'Sinceridad', '', 'Homosexual', 'FALSO', ''),
('1191', 'Quince centimos', 'GARCIA GARC?A', 'VALENT?', 'ALB?NIZ , 22, 2N.', 'Barcelona', 936565874, 0, '', 'Hombre', '0000-00-00', 'Separado/a', 1, 'FALSO', 'Camarero/a', 'FP', 'castellano', 400, 0, 108, 2, 'Otros', 'Azules', 'FALSO', 'Regular', 'Deporte', 'Lectura', 'Sinceridad', 'Fortaleza', 'Serenidad', 'Sinceridad', '', 'Homosexual', 'VERDADERO'),
('1192', 'Rebeca', 'AROCA G?MEZ', 'AINA', 'TRES ROURES , 10, 4T 2A', 'Tarragona', 938205782, 632514125, 'rebeca@cataloniamail.com', 'Mujer', '0000-00-00', 'Separado/a', 0, 'FALSO', '', 'FP', 'catal?n', 500, 0, 95, 2, 'Pelirrojo', 'Otro', 'VERDADERO', 'Buena', 'Deporte', 'Cine', 'Serenidad', 'Inteligencia', 'Romanticismo', 'Ternura', '', 'Homosexual', 'VERDADERO'),
('1193', 'Rebelde', 'ALONSO RODRIGUEZ', 'DAVID', 'PROL. PADR? , 1, 2N., 1A.', 'Sevilla', 938305551, 0, 'rebelde@intercom.es', 'Hombre', '0000-00-00', 'Divorciado/a', 2, 'FALSO', '', 'Licenciado/a', 'franc?s', 1500, 0, 83, 2, 'Calvo', 'Verdes', 'FALSO', 'Buena', 'Lectura', 'M?sica', 'Romanticismo', 'Realismo', 'Serenidad', 'Ternura', '', 'Homosexual', 'VERDADERO'),
('1194', 'Recio', 'CANO G?MEZ', 'GERARD', 'ALB?NIZ , 13, 2N., 1A.', 'Zaragoza', 936577225, 0, '', 'Hombre', '0000-00-00', 'Otros', 1, 'FALSO', 'Asesor/a fiscal', 'Doctor/a', 'castellano', 1200, 0, 69, 2, 'Otros', 'Verdes', 'VERDADERO', 'Buena', 'Caminar', 'Deporte', 'Inteligencia', 'Fortaleza', 'Serenidad', 'Ternura', '', 'Heterosexual', 'VERDADERO'),
('1195', 'Recital', 'ALCAIDE MOLINA', 'MARTA', 'FONT DEL GAT , 1', 'Barcelona', 938773647, 632544145, '', 'Mujer', '0000-00-00', 'Separado/a', 0, 'FALSO', 'Camarero/a', 'Elementales', 'catal?n', 400, 0, 73, 2, 'Casta?o;Marrones', 'FALSO', 'Regular', 'Deporte', 'Cine', 'Romanticismo', 'Alegr?a', 'Inteligencia', 'Ternura', '', 'No declarada', 'FALSO', ''),
('1196', 'Rene', 'AGUILERA PRAT', 'MIREIA', 'MONTCAU , 1', 'Barcelona', 938208054, 0, 'rene@intercom.es', 'Mujer', '0000-00-00', 'Soltero/a', 1, 'VERDADERO', '', 'Elementales', 'catal?n', 600, 24100, 90, 2, 'Negro', 'Marrones', 'FALSO', 'Buena', 'Deporte', 'Caminar', 'Sencillez', 'Fortaleza', 'Ternura', 'Ternura', '', 'No declarada', 'VERDADERO'),
('1197', 'Repic?;ALAPONT ICART', 'ELOI', 'MONTURIOL , 1', 'Barcelona', '938208054', 658789875, 0, 'Hombre', '09/03/66', '0000-00-00', '1', 0, '', 'EGB', 'catal?n', '1300', 102200, 58, 2, 0, 'Marrones', 'FALSO', 'Buena', 'Cine', 'M?sica', 'Realismo', 'Sinceridad', 'Sinceridad', 'Sinceridad', '', 'Homosexual', 'VERDADERO', ''),
('1198', 'Rica', 'RIVERO FLORIDO', 'ANNA', 'VILATORRADA , 6', 'Valencia', 930712563, 654112144, 'rica@terra.es', 'Mujer', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Comercial', 'Diplomado/a', 'castellano', 700, 0, 102, 2, 'Otros', 'Marrones', 'FALSO', 'Fatal', 'M?sica', 'TV', 'Sinceridad', 'Romanticismo', 'Inteligencia', 'Sinceridad', '', 'Bisexual', 'VERDADERO'),
('1199', 'Rockera', 'AVILA MASJUAN', 'ALBA', 'JAUME GALOBART , 11', 'Valencia', 938204078, 0, 'rockera@terra.es', 'Mujer', '0000-00-00', 'Otros', 2, 'FALSO', 'Camarero/a', 'EGB', 'catal?n', 500, 0, 76, 2, 'Otros', 'Negros', 'VERDADERO', 'Regular', 'Lectura', 'TV', 'Ternura', 'Fortaleza', 'Buen Humor', 'Alegr?a', '', 'Bisexual', 'VERDADERO'),
('1200', 'Roma', 'GRANADOS ANDR?S', 'SANDRA', 'SANT GEN?S , 25', 'Barcelona', 936871045, 0, '', 'Mujer', '0000-00-00', 'Divorciado/a', 1, 'FALSO', 'Camarero/a', 'Bachillerato', 'catal?n', 1500, 0, 51, 2, 'Calvo', 'Marrones', 'FALSO', 'Regular', 'Caminar', 'Deporte', 'Alegr?a', 'Sinceridad', 'Serenidad', 'Sencillez', '', 'Heterosexual', 'VERDADERO'),
('1201', 'Roman', 'FERRER GASSET', 'ERIC', 'VERGE DE F?TIMA , 2, 3R., 1A.', 'Valencia', 938745211, 0, 'roman@wandoo.es', 'Hombre', '0000-00-00', 'Otros', 0, 'FALSO', 'Recepcionista', 'EGB', 'castellano', 1400, 0, 62, 2, 'Casta?o;Negros', 'VERDADERO', 'Buena', 'Deporte', 'Caminar', 'Alegr?a', 'Sinceridad', 'Alegr?a', 'Sinceridad', '', 'Homosexual', 'VERDADERO', ''),
('1202', 'Romario', 'AMIGO MODREGO', 'LLU?S', 'JAUME I , 10', 'Zaragoza', 938300065, 654401401, '', 'Hombre', '0000-00-00', 'Divorciado/a', 1, 'FALSO', 'Comercial', 'EGB', 'gallego', 700, 0, 98, 2, 'Rubio', 'Azules', 'FALSO', 'Buena', 'TV', 'Cine', 'Sencillez', 'Fortaleza', 'Sinceridad', 'Alegr?a', '', 'Homosexual', 'FALSO'),
('1203', 'Romeo', 'ABDIN TATJ?', 'CRISTIAN', 'SANT JOAN , 0, C, 1R., B', 'Sevilla', 938208674, 0, 'romeo@intercom.es', 'Hombre', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Asesor/a fiscal', 'Elementales', 'catal?n', 1100, 0, 76, 2, 'Calvo', 'Marrones', 'VERDADERO', 'Excelente', 'Lectura', 'TV', 'Realismo', 'Fortaleza', 'Alegr?a', 'Romanticismo', 'Las mujeres', 'Heterosexual', 'VERDADERO'),
('1204', 'Romesco', 'CANELLAS GOMEZ', 'GUILLEM', 'JACINT VERDAGUER , 13', 'Zaragoza', 930214054, 0, '', 'Hombre', '0000-00-00', 'Separado/a', 0, 'FALSO', 'Administrativo/a', 'Elementales', 'catal?n', 400, 0, 68, 2, 'Calvo', 'Verdes', 'FALSO', 'Regular', 'M?sica', 'TV', 'Inteligencia', 'Buen Humor', 'Serenidad', 'Realismo', '', 'Heterosexual', 'VERDADERO'),
('1205', 'RONC', 'HIDALGO ALTIMIRAS', 'DIMAS', 'SANT BENET , 28, 2N., 2A.', 'Barcelona', 936521404, 602120214, 'ronc@cataloniamail.com', 'Hombre', '0000-00-00', 'Otros', 0, 'VERDADERO', '', 'Bachillerato', 'catal?n', 1400, 66800, 89, 2, 'Rubio', 'Marrones', 'FALSO', 'Buena', 'Deporte', 'M?sica', 'Ternura', 'Buen Humor', 'Alegr?a', 'Inteligencia', '', 'Heterosexual', 'VERDADERO'),
('1206', 'Sabrosa', 'BASTARDAS FRANCH', 'ANA IN?S', 'FONERIA , 12', 'Zaragoza', 938350593, 0, 'sabrosa@hotmail.com', 'Mujer', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Abogado/a', 'FP', 'catal?n', 1400, 0, 96, 2, 'Negro', 'Marrones', 'FALSO', 'Regular', 'TV', 'M?sica', 'Alegr?a', 'Inteligencia', 'Alegr?a', 'Sencillez', 'Viajar en avi?n;Heterosexual', 'VERDADERO', ''),
('1207', 'Salsa', 'ABADIAS MASANA', 'IVET', 'ALFONS XII , 9, 4T 1A', 'Zaragoza', 939962045, 622101451, 'salsa@cataloniamail.com', 'Mujer', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Camarero/a', 'EGB', 'catal?n', 1100, 0, 105, 2, 'Casta?o;Azules', 'FALSO', 'Buena', 'Lectura', '#N/A', 'Serenidad', 'Inteligencia', 'Sinceridad', 'Sinceridad', 'Viajar en avi?n;Heterosexual', 'VERDADERO', '', ''),
('1208', 'sandra', 'AREVALO SANCHEZ', 'J?LIA', 'JAUME I , 10', 'Valencia', 938755603, 654874412, '', 'Mujer', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Recepcionista', 'FP', 'catal?n', 1300, 0, 99, 2, 'Casta?o;Marrones', 'VERDADERO', 'Regular', 'Lectura', 'Deporte', 'Serenidad', 'Buen Humor', 'Sinceridad', 'Serenidad', '', 'No declarada', 'FALSO', ''),
('1209', 'Sha', 'ALINS MULET', 'DANIEL', 'DE LA PESCA , 1, 1R., 2A.', 'Barcelona', 938305524, 610025001, '', 'Hombre', '0000-00-00', 'Casado/a', 2, 'FALSO', 'Conductor/a', 'Elementales', 'castellano', 700, 0, 86, 2, 'Rubio', 'Verdes', 'FALSO', 'Regular', 'Deporte', 'Caminar', 'Ternura', 'Sinceridad', 'Inteligencia', 'Romanticismo', '', 'Heterosexual', 'VERDADERO'),
('1210', 'Sincer', 'GARCIA GONZ?LEZ', 'ABEL', 'PIRINEUS , 22', 'Valencia', 936571974, 0, 'sincer@altecom.es', 'Hombre', '0000-00-00', 'Soltero/a', 0, 'VERDADERO', 'Camarero/a', 'Licenciado/a', 'catal?n', 1600, 8500, 83, 2, 'Pelirrojo', 'Azules', 'VERDADERO', 'Regular', 'Cine', 'Deporte', 'Fortaleza', 'Ternura', 'Serenidad', 'Romanticismo', '', 'Homosexual', 'VERDADERO'),
('1211', 'Sincera', 'ALVAREZ PARCERISA', 'IRENE', 'PROL. JACINT VERDAGUER , 1, 3R., 2A.', 'Sevilla', 938300036, 0, 'sincera@hotmail.com', 'Mujer', '0000-00-00', 'Divorciado/a', 1, 'VERDADERO', '', 'EGB', 'castellano', 300, 68000, 98, 2, 'Otros', 'Azules', 'FALSO', 'Regular', 'Caminar', 'Lectura', 'Inteligencia', 'Sencillez', 'Sinceridad', 'Alegr?a', 'Los entierros', 'Bisexual', 'FALSO'),
('1212', 'suau', 'CASAS ANDR?S', 'ADRI?', 'JAUME GALOBART , 14', 'Madrid', 936505455, 0, 'suau@hotmail.com', 'Hombre', '0000-00-00', 'Separado/a', 1, 'FALSO', '', 'Elementales', 'ingl?s', 1300, 0, 100, 2, 'Casta?o;Negros', 'VERDADERO', 'Regular', 'TV', 'Lectura', 'Ternura', 'Sencillez', 'Serenidad', 'Alegr?a', '', 'Homosexual', 'VERDADERO', ''),
('1213', 'Superman', 'MORALES GESE', 'JAIRO', 'SANT JOAN, EDIFICI D , 3R A', 'Barcelona', 936587454, 600541125, 'superman@altecom.es', 'Hombre', '0000-00-00', 'Separado/a', 0, 'FALSO', 'Funcionario/a', 'Bachillerato', 'catal?n', 1300, 0, 85, 2, 'Pelirrojo', 'Negros', 'FALSO', 'Fatal', 'TV', '#N/A', 'Ternura', 'Romanticismo', 'Inteligencia', 'Inteligencia', '', 'No declarada', 'VERDADERO'),
('1214', 'Superwoman', 'BARALD?S MARTORELL', 'CRISTINA', 'VIC , 119, 3R., 2A.', 'Valencia', 938725845, 0, 'superwoman@wandoo.es', 'Mujer', '0000-00-00', 'Soltero/a', 0, 'FALSO', 'Conductor/a', 'Diplomado/a', 'catal?n', 1500, 0, 101, 2, 'Calvo', 'Azules', 'FALSO', 'Excelente', 'TV', 'Cine', 'Alegr?a', 'Buen Humor', 'Buen Humor', 'Realismo', '', 'Homosexual', 'VERDADERO'),
('1215', 'Tablon', 'AROCA G?MEZ', 'DAVID', 'CARLES BU?GAS , 10, 1R., 1A.', 'Barcelona', 938205730, 0, 'tablon@hotmail.com', 'Hombre', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Recepcionista', 'EGB', 'gallego', 900, 0, 58, 2, 'Otros', 'Negros', 'FALSO', 'Buena', 'M?sica', 'Caminar', 'Alegr?a', 'Buen Humor', 'Realismo', 'Serenidad', '', 'Homosexual', 'VERDADERO'),
('1216', 'tendre', 'RUEDA ALVAREZ', 'ADRI?', 'JAUME BALMES , 67, 2N.', 'Madrid', 936828258, 0, 'tendre@terra.es', 'Hombre', '0000-00-00', 'Otros', 1, 'FALSO', '', 'Elementales', 'catal?n', 1500, 0, 76, 2, 'Pelirrojo', 'Verdes', 'FALSO', 'Buena', 'Cine', 'Lectura', 'Sinceridad', 'Romanticismo', 'Inteligencia', 'Serenidad', '', 'Homosexual', 'VERDADERO'),
('1217', 'Teta', 'ALVAREZ DOMENECH', 'LUCIA', 'PROL. PADR? , 1, 3R., 2A.', 'Valencia', 938300045, 0, 'teta@intercom.es', 'Mujer', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Administrativo/a', 'Elementales', 'catal?n', 400, 0, 62, 2, 'Otros', 'Otro', 'VERDADERO', 'Regular', 'Deporte', 'Cine', 'Romanticismo', 'Buen Humor', 'Fortaleza', 'Sinceridad', '', 'Homosexual', 'VERDADERO'),
('1218', 'Tomasa', 'BOIX GONZ?LEZ', 'CARLA', 'DE LA CA?A , 12, 2N., C', 'Tarragona', 936521452, 624487554, 'tomasa@hotmail.com', 'Mujer', '0000-00-00', 'Casado/a', 0, 'FALSO', '', 'Licenciado/a', 'castellano', 700, 0, 49, 2, 'Casta?o;Marrones', 'FALSO', 'Buena', 'TV', 'M?sica', 'Sinceridad', 'Alegr?a', 'Romanticismo', 'Sencillez', 'Los hospitales', 'No declarada', 'VERDADERO', ''),
('1219', 'Tranquil', 'BARALD?S MONR?S', 'ADRI?', 'VIC , 119, 2N., 1A.', 'Valencia', 938725885, 0, '', 'Hombre', '0000-00-00', 'Divorciado/a', 0, 'VERDADERO', 'Funcionario/a', 'FP', 'catal?n', 1100, 90800, 62, 2, 'Calvo', 'Marrones', 'VERDADERO', 'Regular', 'Caminar', 'TV', 'Alegr?a', 'Buen Humor', 'Inteligencia', 'Alegr?a', 'Los hospitales', 'Bisexual', 'VERDADERO'),
('1220', 'Tremenda', 'AGUILERA MERINO', 'MARTA', 'MORAGUES , 1', 'Valencia', 938208303, 621145584, 'tremenda@altecom.es', 'Mujer', '0000-00-00', 'Separado/a', 1, 'FALSO', 'Comercial', 'Bachillerato', 'catal?n', 0, 0, 75, 2, 'Pelirrojo', 'Otro', 'FALSO', 'Regular', 'TV', 'M?sica', 'Serenidad', 'Alegr?a', 'Sinceridad', 'Sencillez', '', 'Heterosexual', 'VERDADERO'),
('1221', 'Tripa', 'BAREA D\'HAENE', 'MARC', 'TRABUCAIRES , 12', 'Valencia', 938360213, 0, 'tripa@intercom.es', 'Hombre', '0000-00-00', 'Casado/a', 0, 'FALSO', 'Administrativo/a', 'EGB', 'castellano', 1600, 0, 74, 2, 'Pelirrojo', 'Marrones', 'FALSO', 'Fatal', 'Caminar', 'Cine', 'Sinceridad', 'Serenidad', 'Sencillez', 'Buen Humor', '', 'Homosexual', 'VERDADERO'),
('1222', 'Verruga', 'BARROSO D\'HAENE', 'ALEX', 'FONERIA , 12', 'Valencia', 938320537, 0, 'verruga@hotmail.com', 'Hombre', '0000-00-00', 'Divorciado/a', 0, 'FALSO', 'Administrativo/a', 'Elementales', 'catal?n', 700, 0, 76, 2, 'Calvo', 'Verdes', 'FALSO', 'Buena', 'TV', 'Lectura', 'Alegr?a', 'Romanticismo', 'Sinceridad', 'Ternura', '', 'Heterosexual', 'VERDADERO');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuario`
--

CREATE TABLE `usuario` (
  `usuario` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `usuario`
--

INSERT INTO `usuario` (`usuario`, `password`) VALUES
('', 'morales'),
('asdsf', 'asdfg'),
('cristian', 'morales'),
('lll', 'mmm'),
('luisa', 'vaquita'),
('lulu', 'luisa');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `personas`
--
ALTER TABLE `personas`
  ADD PRIMARY KEY (`ID`);

--
-- Indices de la tabla `usuario`
--
ALTER TABLE `usuario`
  ADD PRIMARY KEY (`usuario`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
